import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = localFont( {
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
} );
const geistMono = localFont( {
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
} );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
  return (
    <html lang="en">
      <body
        className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }
      >
        <div className="flex h-screen">
          {/* Sidebar */ }
          <Sidebar />

          {/* Main Content */ }
          <main className="flex-grow bg-gray-100 p-8 overflow-y-auto">
            { children }
          </main>
        </div>
      </body>
    </html>
  );
}
